### ISSUE TITLE
xprop: unable to open display

### ISSUE THREAD

**Issue by pesader** [fkrull/vscode-gtk-dark-titlebar#28]
Hello there! First of all, thank you for developing this awesome extension!
I was recently unable to make Dark Titlebar work, and I get this error everytime I enable it: 

```log
.../fkrull.gtk-dark-titlebar-1.3.0-universal/bin/xprop-linux-x64: unable to open display ''
```

Is this a problem on my end?
Thanks in advance!

**Comment by fkrull** [comment]
Weird. What distribution are you using and how did you install VS Code (from the website, Flathub, other 3rd party builds...)?

**Comment by pesader** [comment]
I'm using a third party build ([VSCodium](https://flathub.org/apps/details/com.vscodium.codium)), installed from flathub.

I did a little digging and this seems to be a VSCodium-only problem. I installed your extension on VSCode and it worked perfectly (great work, by the way!).

I then installed Dark Bar (an app with the same proposal as your extension, but for other applications was well) to see if it would work with VSCodium, and for some reason it was not "seeing" the VSCodium window although it was "seeing" the VSCode one.

![image](https://user-images.githubusercontent.com/65264536/203438610-192c297b-ef15-4546-8750-9c77538cbe44.png)
Above to the left is Dark Bar, to the right is VSCodium, and below is VSCode.

Maybe this is a Wayland thing?

**Comment by fkrull** [comment]
> Maybe this is a Wayland thing?

Yeah, it looks like VSCodium is using a Wayland build of Electron or something. The official VSCode builds are still using X11 (even if you're running on Wayland) which is why the xprop trick works.

I guess I'll see what I can figure out. Darkbar claims Wayland support in some form, so maybe I can steal their approach.

**Comment by pesader** [comment]
Weird thing is, DarkBar isn't working on VSCodium either.

> it looks like VSCodium is using a Wayland build of Electron or something.

Good catch, I didn't know that! That's probably the cause of the problem.

**Comment by fkrull** [comment]
Soooo bad news: there doesn't seem to be a way to make this extension work with Wayland windows. Darkbar's "Wayland support" only seems to be for running the Darkbar application itself as a Wayland window. 😕 GTK simply doesn't seem to have an equivalent to the theme variant setting for Wayland windows.

I added a note about the Wayland situation to the readme, but I think that's all I can do here. It might be possible to force Electron to use X11 windows instead of Wayland windows using the `--ozone-platform` flag ([docs](https://chromium.googlesource.com/chromium/src/+/HEAD/docs/ozone_overview.md#x11)), but I couldn't make that work with the VS Codium Flatpak. It always just crashed, possibly because the Flatpak itself sets these flags.

**Comment by pesader** [comment]
Hey, thanks for investigating this!
The GTK_THEME workaround you suggested in the README worked for me :)
